### ISSUE TITLE
The GH Action `run-all` not working correctly

### ISSUE THREAD

**Issue by dj-wasabi** [dj-wasabi/dj-wasabi-release#12]
The GH Action `run-all` seems to not running fine when executing the `run-me.py` script:

```
       - name: Run runme with label script.
        run: ./run-me.py -D -s label.py
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The labels are not found when script is executed.
